name: CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - uses: actions/setup-node@v2

    # - uses: browser-actions/setup-chrome@latest
    # - uses: nanasess/setup-chromedriver@master
    - name: Setup Chrome and chromedriver
      uses: ./.github/actions/setup-chrome

    - name: Run tests
      run: bundle exec rake test
